### PR TITLE
Update Dependecy versions to work with go v1.22 and k8 v1.30.4

### PR DESCRIPTION
**Pull request by zozitak**
Hello,

I did the neccecary changes to work with the latest stable k8 version (1.30.4). 
I tested this build with go v1.22. 

/project_root run:
``` bash
kind create cluster --image kindest/node:v1.30.4
make build
make install
make run
```

### Please review all functionalities, and give feedback on neccecary changes.
@dominis , @mariusrugan, @csomaati, @zsmav, @davidkornel 

#### Problem 1
Controller-tools v0.16 with controller-runtime v0.19 can't generate perfect yml descriptions. 
Controller-gen can't create schemes for more complex validations, like allOf under k8@v1.30.4. 
( protocols allOf is an enum now )
I took the generated file ( amtd.r6security.com_adaptivemovingtargetdefenses.yaml ) 
and patched it in kustomize ( version_update_fix_in_adaptivemovingtargetdefenses.yaml ). 
Relevant links to this particular problem: 
[Issue 444 ->](https://github.com/kubernetes-sigs/controller-tools/issues/444)
[Issue 622 ->](https://github.com/kubernetes-sigs/controller-tools/issues/622)
[CRD API ->](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/)
[extend K8 with CRD - >](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)

#### Promblem 2
Other than problem 1, I changed depricated lines to "newer version same functionality" code.

### Feel free to reach out, and ask questions.

### CODE REVIEW

**Comment by dominis** [comment]
Thank you @zozitak. 

@davidkornel do you have time to review this PR?

**Comment by davidkornel** [comment]
Thank you. @zozitak 
I had a few minutes to check the changed files and the reported issues. So far, LGTM, although I didn't have time to test things out. I can test it tomorrow to see if I catch anything.

Just out of curiosity: Did you know about this CRD generation issue? I didn't. Good catch.

**Comment by zozitak** [comment]
Hello @davidkornel, 
I didn't know. I ran into it. I wanted to "make install", and k8 throw an error after bumbing go to v1.22:

```
The CustomResourceDefinition "adaptivemovingtargetdefenses.amtd.r6security.com" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[strategy].items.properties[action].properties[customAction].properties[ports].items.properties[protocol].allOf[0].default: Forbidden: must be undefined to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[strategy].items.properties[action].properties[customAction].properties[ports].items.properties[protocol].allOf[1].default: Forbidden: must be undefined to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[strategy].items.properties[action].properties[customAction].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

I looked into it, and config/crd/bases/amtd.r6security.com_adaptivemovingtargetdefenses.yaml had a
allOf clause, generated with two default fields. The allOf clause was in ports/protocols, which could be an enum. 
[This line in go 1.22 under k8@1.30.4 ->](https://github.com/r6security/phoenix/blob/291a019c867054386f1828cd431c0caaa49900e8/config/crd/bases/amtd.r6security.com_adaptivemovingtargetdefenses.yaml#L665)
```yaml
protocol:
  allOf:
  - default: TCP
  - default: TCP
  description: |-
    Protocol for port. Must be UDP, TCP, or SCTP.
    Defaults to "TCP".
  type: string
```
and this is the Issue 444

Maybe this could be solved without a kustomize patch, if controller-runtime annotations could be overridden, or the behavior of controller-gen could be changed. I am new to go, so I choose the kustomize patch route.

**Comment by zozitak** [comment]
"v1beta1" isn't supported in k8>v1.22, this will cause problems.

**Pull request closed without merging**
